server:
  # 端口
  port: 8080
  servlet:
    encoding:
      force: true
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/javascript,text/css
    min-response-size: 2048
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    max-connections: 6500
    connection-timeout: 12000

version: 3.1.2
# 默认文件上传地址
web.upload-path: resources/upload/
# 程序升级备份目录
web.backup-path: backup
spring:
  aop:
    proxy-target-class: true
  devtools:
    restart:
      enabled: false
  servlet:
    multipart:
      # 单个文件上传允许最大大小,默认-1为不限制,如需限制大小改为具体的大小即可,如100MB
      max-file-size: -1
      # 总上传的数据大小,默认-1为不限制,如需限制大小改为具体的大小即可,如100MB
      max-request-size: -1
  datasource:
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      web-stat-filter:
        enabled: false
      stat-view-servlet:
        enabled: false
        login-password: 123456
        login-username: perfree
      filters: stat
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
        config:
          enabled: true
        wall:
          enabled: true
          db-type: mysql
          config:
            delete-allow: true
            drop-table-allow: true
            multi-statement-allow: true
  mvc:
    view:
      prefix: /
    servlet:
      load-on-startup: 1
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.perfree.model

#pagehelper配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com.perfree: error
    com.perfree.config.PostAppRunner: info
    com.perfree.Application: info
    com.perfree.plugins: info
  file:
    name: ./logs/Perfree.log
    max-history: 7
    max-size: 10MB
cache:
  ehcache:
    config: ehcache.xml
shiro:
  loginUrl: /login
  enabled: true
  # 会话超时时间(分钟)
  timeout: 120
swagger:
  enable: false
  application-name: PerfreeBlog
  application-version: ${version}
  application-description: PerfreeBlog接口文档
  try-host: http://localhost:${server.port}