server:
  port: 8080

solon:
  app:
    name: perfree
  env: dev
  # 序列化
  serialization:
    json:
      dateAsFormat: yyyy-MM-dd HH:mm:ss # 配置日期格式（默认输出为时间戳）
      dateAsTimeZone: GMT+8 # 配置时区
      #      dateAsTicks: false # 将date转为毫秒数（和 dateAsFormat 二选一）
      longAsString: true # 将long型转为字符串输出（默认为false）
      boolAsInt: false # 将bool型转为字符串输出（默认为false）
      nullStringAsEmpty: false
      nullBoolAsFalse: false
      nullNumberAsZero: false
      nullArrayAsEmpty: false
      nullAsWriteable: false # 输出所有null值
      enumAsName: false # 枚举使用名字
version: 4.0.1

perfree:
  # 是否开启开发环境插件自动更新,当执行build modules时,会自动更新插件
  autoLoadDevPlugin: true
  # 监听插件是否发生改变的时间间隔(毫秒)   默认10秒(根据你的电脑配置改动,编译的快就调短一点)
  autoLoadDevPluginTime: 10000
  # 是否为演示环境
  demoModel: false

solon.dataSources:
  master!:
    class: "com.zaxxer.hikari.HikariDataSource"
    jdbcUrl: jdbc:mysql://192.144.160.229:3306/solon_blog?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: solon_blog
    password: HfzZy43eCJN3bnH2

mybatis:
  configuration:
    map-underscore-to-camel-case: false

mybatis-flex:
  type-aliases-package:
    - com.perfree.model
  mapper-locations:
    - com.perfree.mapper
  configuration: #扩展配置（要与 FlexConfiguration 类的属性一一对应）
    cacheEnabled: false
    mapUnderscoreToCamelCase: false
  global-config:
    key-config:
      key-type: Auto

# 分页插件配置
pagehelper:
  offsetAsPageNum: true
  rowBoundsWithCount: true
  pageSizeZero: false
  reasonable: true
  params: pageNum=pageHelperStart;pageSize=pageHelperRows;
  supportMethodsArguments: false

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:

  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  # 前缀
  token-prefix: Bearer