plugin:
  # 插件id(必须唯一)
  id: perfree-exam
  # 插件名称,
  name: 示例插件
  # 插件mapperXml文件位置, 没有可不写
  mapperLocation: mapper/*.xml
  # 插件描述信息
  description: 描述信息
  # 插件最低支持版本
  minimalVersion: 2.2.0
  # 插件版本
  version: 2.23.0
  # 插件静态资源路径
  staticLocations: classpath:/exam-static/
  # 插件更新url
  updateUrl:
author:
  # 作者名
  name: Perfree
  # 作者邮箱
  email: perfree@126.com
  # 作者网站
  webSite: http://111111