plugin:
  # 插件id(必须唯一)
  id: perfree-plugin-demo
  # 插件名称,
  name: 示例插件
  # 插件mapperXml文件位置, 没有可不写
  mapperLocation: mapper/*.xml
  # 插件描述信息
  description: 描述信息
  # 插件最低支持版本
  minimalVersion: 2.2.0
  # 插件版本
  version: 1.0.2
  # 插件静态资源路径
  staticLocations: /ui/
  # 是否为开发环境(如果是插件前端通过node运行,需要开启dev且设置前端开发环境地址)
  isDev: false
  # 前端开发环境地址
  frontDevAddress: http://127.0.0.1:4202
  # 插件更新url
  updateUrl:
author:
  # 作者名
  name: Perfree
  # 作者邮箱
  email: perfree@126.com
  # 作者网站
  webSite: http://111111